---
title: "plot_da_network"
output: html_document
date: '2023-11-20'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(ggh4x)
library(dplyr)
library(openxlsx)
library(tidyr)
library(igraph)
wb <- loadWorkbook("~/ASMP_Dermotype/Data/3_assoc_diff/co_occurence_result.xlsx")
load("~/ASMP_Dermotype/Data/3_assoc_diff/net_derm_ax.RData")
load("~/ASMP_Dermotype/Data/3_assoc_diff/all_networks_noax_29nov.RData")
source('~/ASMP_Dermotype/Script/Analysis/utils_network_asmp.R')
```

```{r}
sheet_names <- names(wb)
df_list <- lapply(sheet_names, function(sheet) {
  read.xlsx(wb, sheet = sheet)
})
names(df_list) <- sheet_names
df_list <- lapply(df_list, function(df) {
  colnames(df) <- c("Taxa1", "Taxa2", "Cor1", "Cor2", "Padj")
  df
})

assoMat_ac<- data.frame(df_list$Ac_CCREPE)
assoMat_vf<- data.frame(df_list$Vf_CCREPE)
assoMat_ub<- data.frame(df_list$Ub_CCREPE)
assoMat_fo<- data.frame(df_list$Fo_CCREPE)
assoMat_ps<- data.frame(df_list$Ps_CCREPE)
assoMat_sc<- data.frame(df_list$Sc_CCREPE)
assoMat_ax<- data.frame(df_list$Ax_CCREPE)

combined_network <- rbind(assoMat_ac %>% mutate(Site = 'Ac'),
                          assoMat_vf %>% mutate(Site = 'Vf'),
                          
                          assoMat_ub %>% mutate(Site = 'Ub'),
                          assoMat_fo %>% mutate(Site = 'Fo'),
                          
                          assoMat_ps %>% mutate(Site = 'Ps'),
                          assoMat_sc %>% mutate(Site = 'Sc'),
                          assoMat_ax %>% mutate(Site = 'Ax'))

 oral <- c('S. mitis oralis pneumoniae', 'S. salivarius', 'R. dentocariosa',
           'V. parvula', 'C. matruchotii', 'R. aeria', 'C. durum',
           'A. viscosus', 'R. mucilaginosa', 'P. melaninogenica',
           'S. sanguinis', "N. flavescens", "A. massiliensis")
 corynebact <- c('C. tuberculostearicum', 'C. pseudogenitalium',
                 'C. kroppenstedtii', 'C. accolens', 'C. jeikeium', 'C. durum', 'C. matruchotii')
 staph <- c('S. hominis', 'S. epidermidis', 'S. haemolyticus', 'S. saprophyticus',
            'S. caprae capitis')
 cuti <- c('C. acnes', 'C. avidum', 'C. granulosum')
 malass <- c('M. restricta', 'M. furfur', 'M. globosa', 'M. japonica', 'M. dermatis', 'M. sloofiae')
 strep <- c('S. mitis oralis pneumoniae', 'S. salivarius', 'S. sanguinis')
 rothia <- c('R. dentocariosa','R. aeria','R. mucilaginosa')
 microco <- c('M. luteus')
 morax <- c('M. osloensis')

 common_skin <- 'Corynebacterium\nStaphylococcus\nMalassezia'
 oral_skin <- 'Streptococcus\nRothia\nCorynebacterium\nPrevotella\nActinomyces\nVeilonella'

# add category for better visualization
combined_network <- combined_network %>%
  mutate(Category = case_when((Taxa1 %in% oral) & (Taxa2 %in% oral)~ oral_skin,
                           grepl('acnes', Taxa1) ~ 'C. acnes',
                           grepl('acnes', Taxa2) ~ 'C. acnes',
                           (Taxa1 %in% c(corynebact, staph, malass, microco, morax)) &
                           (Taxa2 %in% c(corynebact, staph, malass, microco, morax)) ~ common_skin,
                           TRUE ~ 'Others'))
p_filt <- 0.1
combined_network_filt <- combined_network %>% 
    tidyr::unite(Interaction, c("Taxa1", "Taxa2"), sep = '-') %>% 
    #mutate(Interaction = rearrange_names(Interaction)) %>% 
  filter(Padj <p_filt) %>% 
  dplyr::select(-Padj)
```


# Use igraph

## AC
```{r}
attr_ac_1 <- generate_nodes_edges(assoMat_ac, 'Cor1')
sub.g.ac.1 <- modif_graph(attr_ac_1)

attr_ac_2 <- generate_nodes_edges(assoMat_ac, 'Cor2')
sub.g.ac.2 <- modif_graph(attr_ac_2)

# #---- to get the coordinates for nodes------#
# #-----adjust nodes position manually -----#
# tkplot(sub.g.ac.1, 
#      edge.width = E(sub.g.ac.1)$weight,
#      #layout = layout.fruchterman.reingold(sub.g.ac.1),
#      layout = coords,
#      vertex.size = set_nodesize(net_derm_ac$normCounts1, sub.g.ac.1),
#      vertex.shape = ifelse(V(sub.g.ac.1)$label %in% oral, "square", "circle"), 
#      vertex.label.dist=1.1, 
#      vertex.label.degree = 1.52*pi,
#      vertex.label.font = 3,
#      vertex.label.color = "black"
#      )
# tkplot(sub.g.ac.2, 
#      edge.width = E(sub.g.ac.2)$weight,
#      #layout = layout.fruchterman.reingold(sub.g.ac.2),
#      layout = coords,
#      vertex.size = set_nodesize(net_derm_ac$normCounts2, sub.g.ac.2),
#      vertex.shape = ifelse(V(sub.g.ac.1)$label %in% oral, "square", "circle"), 
#      vertex.label.dist=1.1, 
#      #vertex.label.cex = 1.3,
#      vertex.label.degree = 1.52*pi,
#      vertex.label.font = 3,
#      vertex.label.color = "black"
#      )
# #-----extract the node coordinates-------#
# # coords <- tk_coords(6)
# write_tsv(data.frame(coords), './assoc_diff/ac_coords.tsv')

#------after arranging nodes to ideal positions, we plot them side by side ----#
coords <- read_tsv('~/ASMP_Dermotype/Data/3_assoc_diff/ac_coords.tsv') %>% as.matrix()

#svg(file="./Ac-network.svg", width=16, height=7)
par(mfrow=c(1,2), mar=c(0,0,0,2))

plot(sub.g.ac.1,
     edge.width = E(sub.g.ac.1)$weight,
     # layout = layout.fruchterman.reingold(sub.g.ac.1),
     layout = coords,
     vertex.size = set_nodesize(net_derm_ac$normCounts1, sub.g.ac.1),
     vertex.shape = ifelse(V(sub.g.ac.1)$label %in% oral, "square", "circle"),
     vertex.label.dist=1.1,
     vertex.label.cex = 1.4,
     vertex.label.degree = 1.52*pi,
     vertex.label.font = 3,
     vertex.label.color = "black",
     xlim = c(-1,1)
     )

plot(sub.g.ac.2, 
     edge.width = E(sub.g.ac.2)$weight,
     # layout = layout.fruchterman.reingold(sub.g.ac.2),
     layout = coords,
     vertex.size = set_nodesize(net_derm_ac$normCounts2, sub.g.ac.2),
     vertex.shape = ifelse(V(sub.g.ac.1)$label %in% oral, "square", "circle"), 
     vertex.label.dist=1.1, 
     vertex.label.cex = 1.4,
     vertex.label.degree = 1.52*pi,
     vertex.label.font = 3,
     vertex.label.color = "black"
     )
dev.off()
```
